[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Mobile Robot Simulator"
description = "The simplest python extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Path (relative to the root) of changelog
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Simulation"

# Keywords for the extension
keywords = ["robotics", "husky", "Franka Research 3", "QCar", "Robot Arm", "4 differential robot", "Ackermann Robot"]

# Icon to show in the extension manager
icon = "data/robot.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"


# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.isaac.core" = {}
"omni.ui.scene" = {}
"omni.kit.window.viewport" = {}
"omni.anim.navigation.bundle" = {}
"omni.anim.people" = {}
"omni.anim.timeline" = {}
"omni.anim.graph.bundle" = {}
"omni.anim.graph.core" = {} 
"omni.anim.graph.ui" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.mobile.robots"

[python.pipapi]
requirements = ["numpy", "scipy", "pymavlink", "pyyaml"]
use_online_index = true

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
